### ISSUE TITLE
Compile binaries for both byuu and higan in nightly releases

### ISSUE THREAD

**Issue by byuu** [higan-emu/higan#1]
Both byuu and higan are derived from the same codebase, and as such have been merged into higan-emu here. However, the Cirrus CI build rules currently only build higan and icarus.

Ideally, we would have separate nightly builds for both byuu and higan, as it might prove confusing to have both emulators in the same download archive. After that, we would want to update the README.md file to provide links to both nightly builds.

I'm not sure of the best way to go about doing this, so I'll leave this task to you all, sorry ^-^;

Note that byuu does not require the icarus binary to be built and included separately, because it is hard-coded into the application itself. Also note that neither higan nor byuu should ship with genius being built as a binary, since it is really only of use to me, and included for historical purposes.

To clarify, icarus is higan's game importer, and genius is icarus' database editor.

**Comment by Screwtapello** [comment]
@byuu, I understand byuu-the-emulator does not require icarus, but does it require the icarus Firmware directory, or higan's System/Systems/Templates directories, or `paths.bml` in general?

**Comment by Screwtapello** [comment]
byuu replied on Discord:

> I believe byuu-the-emulator can benefit from the Firmware directory (though it embeds the legal files directly into the binary, it will look there for `dsp*.program|data.rom`, etc.)
> It does not care about Templates or `paths.bml` at all

**Comment by Screwtapello** [comment]
I have been experimenting with an updated `.cirrus.yml` file that builds genius, higan, and byuu separately (and does not create downloadable artifacts for genius). The resulting artifacts can be downloaded from these links; I'd appreciate it if people could test the byuu build for their platform, and verify the higan build still works (at least as well as the current nightlies do, anyway):

https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/linux-x86_64-binaries/higan-nightly/higan-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/linux-x86_64-binaries/byuu-nightly/byuu-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/freebsd-x86_64-binaries/higan-nightly/higan-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/freebsd-x86_64-binaries/byuu-nightly/byuu-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/windows-x86_64-binaries/higan-nightly/higan-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/windows-x86_64-binaries/byuu-nightly/byuu-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/macOS-x86_64-binaries/higan-nightly/higan-nightly.zip?branch=ci-updates
https://api.cirrus-ci.com/v1/artifact/github/Screwtapello/higan/macOS-x86_64-binaries/byuu-nightly/byuu-nightly.zip?branch=ci-updates
