### ISSUE TITLE
Command Line Trigger - Better integration with Emulator Frontend

### ISSUE THREAD

**Issue by sidamo82** [higan-emu/higan#11]
Hi everybody,

I try to integrate higan on my linux arcade cabinet, but actually I can't do it, because higan can be used only inside a Desktop Enviroment (Gnome / XFCE / etc.). 

If it try to run it directly from X Server I see error:

The program 'higan' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 9 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

In next release I suggest to improve higan to run game directly on X Server, without have to run it inside Desktop Manager. This can be great feature  in order to use it inside an arcade cabinet and launch games directly from HyperSpin or AttractMode frontends.

**Comment by AndersonTorres** [comment]
Well, I think it can be done by porting hiro. As I am studying its sources, it is as easy as to create a directory implementing a new hiro toolkit that uses only X directives.

Unfortunately I am not so good at creating those things alone.

**Comment by Screwtapello** [comment]
I can reproduce this crash:

- Run `Xephyr :2 -resizable` to launch a new X11 server, without a window manager, in a window
- Run `DISPLAY=:2 xlogo` to verify that external apps can connect to the nested X11 server and display things
- Run `DISPLAY=:2 higan` to run higan inside the nested X11 server

Despite the instructions in the error message, running `higan --sync` does nothing, because higan does not pass its command-line arguments to GTK, it always passes a synthetic list instead. However building higan with `build=debug` causes it to add `--sync` to that synthetic list, for the same effect.

**Comment by Screwtapello** [comment]
After building in debug mode and installing GTK debug symbols so I could break on `gdk_x_error()`, I discovered that the offending code is [in `hiro::pDesktop::workspace()`](https://github.com/higan-emu/higan/blob/master/hiro/gtk/desktop.cpp#L29), where higan attempts to read the `_NET_WORKAREA` property from the root window.

[`_NET_WORKAREA`](https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html#idm46094431924464) should be set by the window manager to record the available desktop area; that is, the screen size minus any room reserved for panels or task bars or whatever. Of course, in a bare X11 server there *is* no window manager, so the property is not available, so it's not wholly surprising higan crashes.

It's still a little bit surprising, though. For one, higan seems to have [error handling code](https://github.com/higan-emu/higan/blob/master/hiro/gtk/desktop.cpp#L42-L46) that should be used if the `_NET_WORKAREA` property couldn't be retrieved.
