### ISSUE TITLE
libgtksourceview-2.0.so.0 is missing

### ISSUE THREAD

**Issue by bodhi-baum** [higan-emu/higan#117]
Downloaded higan as well as byuu nightly from 2020-10-03, but both of them won´t run on my Linux Mint 20 claiming that libgtksourceview-2.0.so.0 is not found.

**Comment by asuramaru** [comment]
Try running sudo apt-get install libgtksourceview2.0 libgtksourceview2.0-dev

**Comment by Screwtapello** [comment]
At least on Debian, it's `sudo apt-get install libgtksourceview2.0-0`

**Comment by bodhi-baum** [comment]
That helped :-)

**Comment by Screwtapello** [comment]
Glad to hear you got it sorted!

**Comment by drone1** [comment]
Hi, I'm on Ubuntu 22.04 and am having trouble with this.

I downloaded the nightly build today (2022-10-07) and am trying to run due to this error and ``apt`` doesn't know about ``libgtksourceview2.0-0`` it seems:

```
➜  ./higan
./higan: error while loading shared libraries: libgtksourceview-2.0.so.0: cannot open shared object file: No such file or directory
➜  sudo apt-get install libgtksourceview2.0-0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgtksourceview2.0-0
E: Couldn't find any package by glob 'libgtksourceview2.0-0'
E: Couldn't find any package by regex 'libgtksourceview2.0-0'
```

The only packages I see are the following and I'm not sure any of them are what I want:

```
➜ apt list | grep libgtksourceview

libgtksourceview-3.0-1/jammy 3.24.11-2build1 amd64
libgtksourceview-3.0-common/jammy,jammy 3.24.11-2build1 all
libgtksourceview-3.0-dev/jammy 3.24.11-2build1 amd64
libgtksourceview-3.0-doc/jammy,jammy 3.24.11-2build1 all
libgtksourceview-4-0/jammy,now 4.8.3-1 amd64 [installed,automatic]
libgtksourceview-4-0/jammy 4.8.3-1 i386
libgtksourceview-4-common/jammy,jammy,now 4.8.3-1 all [installed,automatic]
libgtksourceview-4-dev/jammy 4.8.3-1 amd64
libgtksourceview-4-dev/jammy 4.8.3-1 i386
libgtksourceview-4-doc/jammy,jammy 4.8.3-1 all
libgtksourceview-5-0/jammy-updates 5.4.1-0ubuntu1 amd64
libgtksourceview-5-common/jammy-updates,jammy-updates 5.4.1-0ubuntu1 all
libgtksourceview-5-dev/jammy-updates 5.4.1-0ubuntu1 amd64
libgtksourceview-5-doc/jammy-updates,jammy-updates 5.4.1-0ubuntu1 all
libgtksourceviewmm-3.0-0v5/jammy 3.18.0-4build1 amd64
libgtksourceviewmm-3.0-dev/jammy 3.18.0-4build1 amd64
libgtksourceviewmm-3.0-doc/jammy,jammy 3.18.0-4build1 all
```

Thank you!

**Comment by Screwtapello** [comment]
If you're willing to build things from source, you can try building higan from source with `make hiro=gtk3` which should make it use libgtksourceview-3.0 instead.

**Comment by drone1** [comment]
Thank you both for your suggestions.

I'm attempting to build from source but having some trouble: I'm following the instructions found in [the docs](https://higan.readthedocs.io/en/stable/install/linux/#compiling-from-source-on-linux), which suggest running the following command: 
```
sudo apt-get install build-essential libgtk2.0-dev libpulse-dev \
    mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl1.2-dev \
    libxv-dev libao-dev libopenal-dev libudev-dev
```
OK, but on Ubuntu 22.04 this won't work as is no surprise to readers of this thread. So I've run:
```
sudo apt-get install build-essential libgtk-3-dev libpulse-dev \
    mesa-common-dev libgtksourceview3.0-dev libcairo2-dev libsdl1.2-dev \
    libxv-dev libao-dev libopenal-dev libudev-dev
```

OK great. But now when I clone, then ``cd`` into the repo root dir and run ``make hiro=gtk3`` (as per your suggestion, @Screwtapello ), I get an error:
```
➜  higan git:(master) make hiro=gtk3
make: *** No targets specified and no makefile found.  Stop.
```
...and just for fun, if I just try to run the suggested make command and see how far I can get, I get an error about unknown platform:
```
➜  higan git:(master) make -C higan 
make: Entering directory '/home/jonl/.local/higan/higan'
GNUmakefile:10: *** "unsupported platform".  Stop.
make: Leaving directory '/home/jonl/.local/higan/higan
```
I saw there's a [thread about this](https://www.linuxquestions.org/questions/showthread.php?p=6282383#post6282383) but no one replied.

Any suggestions?

**Comment by FabioLolix** [comment]
Try to use   `make -C higan-ui hiro=gtk3`

That's what I'm using [here](https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/h/higan-gtk-git/PKGBUILD) to build higan with gtk

**Comment by drone1** [comment]
> Try to use   `make -C higan-ui hiro=gtk3`
> 
> 
> 
> That's what I'm using [here](https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/h/higan-gtk-git/PKGBUILD) to build higan with gtk

Thanks a lot, this worked!

**Comment by rrocharoberto** [comment]
I think there is no documentation regarding this missing library.
Could someone please include this information in the README.md file?

**Comment by negsi** [comment]
> Try to use `make -C higan-ui hiro=gtk3`
> 
> That's what I'm using [here](https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/h/higan-gtk-git/PKGBUILD) to build higan with gtk

Working on Linux Mint 22.1 Xia. Thank you very much. 👍
