### ISSUE TITLE
Fix default bindings for byuu UI

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/higan#119]
In 7d68836d we changed the names the byuu UI uses to describe the input bindings it offers. However, the default bindings we ship with nightlies (in `extras/byuu/settings.bml`) were not updated, so nightlies no longer have any default bindings on Windows.

The default bindings also seem to be Windows-specific, but I'm not sure what we can do about that. byuu-UI allows multiple alternative bindings for each input, perhaps we could set them to the Windows, Linux, and macOS syntaxes respectively?

**Comment by Kawa-oneechan** [comment]
Sounds like a plan to me.

**Comment by Screwtapello** [comment]
Closing this issue since the "byuu" UI has been removed from higan; it will continue as part of Near's "ares" project,
