### ISSUE TITLE
Query: How do I use the cheats and find the battery save

### ISSUE THREAD

**Issue by SykkNyzz** [higan-emu/higan#120]
Tried following the guide, missing the ability to do either. Advice please.

**Comment by Screwtapello** [comment]
If you open the Help menu, does it say "About byuu ..." or "About higan-ui ..."?

**Comment by SykkNyzz** [comment]
about lucia

**Comment by Screwtapello** [comment]
I'm afraid byuu/lucia does not support cheats.

Battery saves should be stored beside the ROM file, with a `*.srm` or `*.sav` extension. If the ROM file is inside a ZIP file, the save file will be beside the ZIP, not inside it.

Thanks for trying higan, and feel free to re-open this issue if you have more questions.
