### ISSUE TITLE
node/video/screen.cpp: color bleed mask is incorrect

### ISSUE THREAD

**Issue by near-san** [higan-emu/higan#148]
https://github.com/higan-emu/higan/blob/master/higan/higan/node/video/screen.cpp#L100

    uint32 mask = 1 << 24 | 1 << 16 | 1 << 8 | 1 << 9;

Should be:

    uint32 mask = 1 << 24 | 1 << 16 | 1 << 8 | 1 << 0;

It should be the same as:

https://github.com/higan-emu/higan/blob/master/higan/higan/node/video/screen.cpp#L90

**Comment by Kawa-oneechan** [comment]
Little tiny fix before bed, just what the doctor ordered.

**Comment by near-san** [comment]
Much obliged, thank you ^-^
