### ISSUE TITLE
Importing games with Icarus doesn't work in macOS 15 Catalina

### ISSUE THREAD

**Issue by quinton-ashley** [higan-emu/higan#16]
I've used wine with higan/icarus on past versions of macOS and it worked.  When I use `wine64 ./icarus.exe` both the gui and command line fail to import any Super Nintendo games.

**Comment by Screwtapello** [comment]
When you run icarus from the command-line, what exact command-line do you use? What error messages are displayed?

**Comment by quinton-ashley** [comment]
I found out it wasn't a problem that was specific to macOS or using it with wine.  Icarus just fails to import half of the snes games I have.  It says "no program.rom found" when I try to do it with the ui.
