### ISSUE TITLE
WonderSwan emulation looks for the boot ROM in the current directory

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/higan#160]
Steps to reproduce:

- download the latest higan nightly
- confirm that `Templates/WonderSwan/boot.rom` exists
- create a new WonderSwan system
- launch it

Expected results:

- system is loaded

Actual results:

- a message box appears, saying "Missing required file: `boot.rom` Would you like to browse for this file now?"
- if you browse to the file in question, it saves it to the working directory rather than to `Systems/WonderSwan`
- If you manually copy `boot.rom` into `Systems/WonderSwan` it still complains about it being missing

**Comment by LukeUsher** [comment]
At the time load is called, the location attribute hasn't been set yet (it's set 'after' calling load, which makes sense, you can't set an attribute on a node that hasn't been created yet!), meaning that loading files from within the load() function will not use the correct path.

This is not a problem with the simple UI as each system has it's own interface which specifies a specific load folder: It's only an issue with the generic method used in the higan-style UI.

A potential workaround would be to load firmware at the power() stage, which is what I did with PolyBlast, but I'm not sure that's the best solution.
