### ISSUE TITLE
Graphical corruption/flickering when riding a dragon in Secret of Mana (USA)

### ISSUE THREAD

**Issue by jjohnson652** [higan-emu/higan#170]
[Observed](url) in byuu v115.
The "flat world map" in Secret of Mana fails to load. Observed with two different copies of the ROM.  Savestate attached to assist with debugging.

Steps:
(1) Summon Flammie using the Flammie/Wind Drum.  (Not necessary in savestate - already summoned.)
(2) Press Start to access spherical world map.
(3) Press R.  This is supposed to (very slowly) load a flat version of the world map, as seen at 8:44 of this video: https://www.youtube.com/watch?v=cF-V7q2LZMs.  However, it fails to load (black screen and soft lock).

Savestate link: https://1drv.ms/u/s!AjRQX6iM6vWG3DYWZI5hW80n0gZy?e=XHsvdg

**Comment by Screwtapello** [comment]
Thank you for taking the time to report an issue! Unfortunately the "byuu" user-interface is now part of [ares](https://ares.dev), not higan, and ares no longer supports v115 save-states. Can you provide an in-game save?

**Comment by jjohnson652** [comment]
Sorry about that!  I thought I recalled byuu was a fork of higan, not ares.  Nevertheless this only matters if it still occurs in the latest version.  I wouldn't be surprised if the same error occurs in higan; might be worth testing.  The function that calls the map seems unusual and I don't recall an entire large Mode 7 map drawn in similar fashion in any other game.

Anyway, here is an in-game save you can use: https://1drv.ms/u/s!AjRQX6iM6vWG3Dfz7lDP6_ZDj9ba?e=Y96Wly

**Comment by Screwtapello** [comment]
Yes, byuu was a fork of higan, but then it forked even further to become ares. Thanks for the in-game save, I'll try it out.

**Comment by jjohnson652** [comment]
Aha! Glad to know I was not completely off-base there.  To be clear, this save file was actually created in "Secret of Mana Relocalized", which is supposed to be identical to the commercial Secret of Mana except for an improved translation and font.  The save loads just fine in the commercial version - and the same soft lock is observed there - but thought I should mention this in case it is a factor.

**Comment by Screwtapello** [comment]
OK, for future reference, after loading the given save file in the latest higan nightly:

- walk south out of the building
- hit X to open up the ring menu
- hit Up to switch from switch-weapons mode to switch-items mode
- hit Right a couple of times to select the yellow Flammie Drum (looks like a [pellet-drum](https://en.wikipedia.org/wiki/Pellet_drum) or a lollipop)
- hit A to summon Flammie and be whisked into the air

The background flickers heavily to black here:
![image](https://user-images.githubusercontent.com/1450918/113251234-aa8a9980-930d-11eb-915c-1d299f0b14c1.png) ![image](https://user-images.githubusercontent.com/1450918/113251277-bece9680-930d-11eb-8503-ca6c18f1f656.png)

- Hold B to increase altitude, and eventually the game stops flickering black, and starts flickering to... heavily zoomed-out Mode 7?

![image](https://user-images.githubusercontent.com/1450918/113251468-09e8a980-930e-11eb-8537-7c47454f9d94.png)

- hit Start to view the world map as a sphere:

![image](https://user-images.githubusercontent.com/1450918/113251554-33a1d080-930e-11eb-8ccd-43068587318c.png)

- hit R to switch to a rectangular projection:

![image](https://user-images.githubusercontent.com/1450918/113251634-58964380-930e-11eb-97c6-366cf8ec1e54.png)

So, the rectangular world-map works properly in higan, but it seems there's other issues here that need looking into.

**Comment by Screwtapello** [comment]
For the record, it seems the game works flawlessly in the latest bsnes nightly, in both "fast" and "accurate" modes. Where higan has full-screen flickering, bsnes shows a flickering shadow of the dragon on the ground (maybe a sprite?).

**Comment by Screwtapello** [comment]
I did manage to reproduce the behaviour you originally described in ares, so I've filed an issue over there too.

**Comment by jjohnson652** [comment]
Very interesting...I didn’t expect the higan results at all. If necessary, I have the cart on an SNES hooked up to my machine and can check on points such as the flickering shadow. (Hopefully the save game battery hasn’t died so there’s a game available for a quick check!)

Thanks for this.

**Comment by Screwtapello** [comment]
The ever-helpful @jbo-85 pointed out on Discord that this is fallout from commit 44cbb88, an attempt at porting https://github.com/bsnes-emu/bsnes/commit/4f7a269ba5d053bb824b5ffa0978799331a5f2d8 to higan. I guess Secret of Mana gets added to the list of games that do goofy things when auto joypad polling isn't quite right. I guess I need to sit down and figure out how to port those changes properly.

**Comment by jjohnson652** [comment]
How interesting!  I never would have guessed the two would be related.  In a way I'm not surprised, though; Secret of Mana is notoriously glitchy (particularly on wrong palettes or sprites, and other display issues), in part because it originally was designed for the cancelled SNES-CD and had to be chopped up on short notice when that project fell through.  Its finickyness may prove a good test case for issues like this.

**Comment by near-san** [comment]
This is a little more complicated than that. It works correctly on ares with the accuracy PPU, but with the scanline PPU the image is nearly (but not quite) pitch black. After the flat map finishes rendering the game is usable without locking. The parameters to the directColor() function were backwards in the scanline renderer. It should be lik ethis:

    mosaicColor = ppu.dac.directColor(mosaicPalette, paletteNumber);

![Screenshot_2021-04-02_00-45-27](https://user-images.githubusercontent.com/77224854/113394329-8bc8e900-9387-11eb-9970-eb17325b835e.png)

Something I noticed in my testing was that if I made $4212.d0 always return 1, the game deadlocks and shows a garbled sky like in your second bugged screenshot, Screwtape.

I'll try to investigate what's going on with higan as well.

**Comment by qeeg** [comment]
> The ever-helpful @jbo-85 pointed out on Discord that this is fallout from commit [44cbb88](https://github.com/higan-emu/higan/commit/44cbb88d49d5a77f19e353fad4bc7fbab6909ca9), an attempt at porting [bsnes-emu/bsnes@4f7a269](https://github.com/bsnes-emu/bsnes/commit/4f7a269ba5d053bb824b5ffa0978799331a5f2d8) to higan. I guess Secret of Mana gets added to the list of games that do goofy things when auto joypad polling isn't quite right. I guess I need to sit down and figure out how to port those changes properly.

That is... REALLY strange as I basically just used the exact same code as bsnes...
