### ISSUE TITLE
Looking for advice on how to install on windows

### ISSUE THREAD

**Issue by KirbyFan102** [higan-emu/higan#18]
What the title says. This is my first time compiling anything.

**Comment by MerryMage** [comment]
There's a windows download (of v110) available here: https://byuu.org/download/higan/higan_v110-windows.zip

**Comment by KirbyFan102** [comment]
Huh. I thought that website was deprecated by now, what with the move to github. But okay, I'll download this version. Thanks!

**Comment by MerryMage** [comment]
Just updated things so they'll now be available here: https://github.com/higan-emu/higan/releases/latest

**Comment by KirbyFan102** [comment]
You should do the same for the bsnes repository, too. It'd be nice to be able to download it standalone.
