### ISSUE TITLE
[Question] what does the word higan mean?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [higan-emu/higan#186]
What does it mean?

**Comment by jeffythedragonslayer** [comment]
emulator-zone claims it means "Hero of Fire."

https://www.emulator-zone.com/snes/higan

**Comment by jchv** [comment]
Yeah, that's the etymology behind the name of the protagonist of Tengai Makyou Zero. I think initially, Near was vague/perhaps coy? about the connection to Tengai Makyou Zero, but it's pretty transparently obvious.
