### ISSUE TITLE
bsnes 115: Timing issue in Bahamut Lagoon

### ISSUE THREAD

**Issue by jjohnson652** [higan-emu/higan#189]
Not sure if you're still accepting issue reports on bsnes v115, but I haven't installed or configure higan.  (Never had any luck figuring out the UI!)  So I'm not sure if it's impacted.

In Bahamut Lagoon patched with Near's English translation and with mostly default settings (Run-Ahead disabled, OpenGL 3.2 video, WASAPI 48k 0 latency audio, Audio synchronized), I've noticed a single video/audio sync issue in nearly 2 full playthroughs.

When the player summons Leviathan, the summoning effect uses a combination of Mode 7 and sprites (I think).  At the end, it is clear that the large polygon is supposed to appear on-screen at the same time as a sound effect, but the polygon appears 1/4 to 1/2 second after said effect.

I provided a savestate for you to test with.  All you have to do is push A (B on an Xbox controller).
[Bahamut Lagoon.zip](https://github.com/higan-emu/higan/files/8405576/Bahamut.Lagoon.zip)

**Comment by Screwtapello** [comment]
Hey, thanks for reporting this issue. I'm not actively dealing with issues in bsnes or higan right now, but I do want to keep collecting (potential) issues in case somebody with the time and energy to properly investigate them comes along.

As such, could you please copy this issue to [the bsnes issue tracker](https://github.com/bsnes-emu/bsnes/issues/)? Just to keep all the bsnes-related stuff together.

**Comment by jjohnson652** [comment]
Done! Thanks.
