### ISSUE TITLE
Add .gitignore rules for byuu

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/higan#19]
Currently, building byuu leaves an untracked `higan/out/byuu` file. We should add it to the `higan/out/.gitignore` file.

If #7 renames byuu before this issue is fixed, obviously the name change applies here too.

**Comment by MerryMage** [comment]
One could ignore everything under `higan/out/*`.

**Comment by Screwtapello** [comment]
If all the contents of `higan/out/` are ignored, the directory vanishes (because git only tracks file contents, not directories), and the build fails because it tries to write to a directory that doesn't exist.

There are other ways to clean this up, but this is the way that meant I didn't have to talk byuu into changing his workflow to suit Git. Maybe this is the time to change some of those policies? Or maybe not.

**Comment by moon-chilled** [comment]
Ignoring `higan/out/*` is fine.  `.gitignore` is a user-interface-level configuration, it doesn't actually affect file tracking.  Notably, since `higan/out/.gitignore` already exists, adding `higan/out` to .gitignore won't remove it.

**Comment by Screwtapello** [comment]
I've been bitten before by `.gitignore` files that ignore themselves. It's been a while, but I recall symptoms like modifications being ignored by `git status` and `git commit -a`, and that's a pain.

Luckily, it turns out the git ignore syntax can have exceptions, so I can ignore everything but `.gitignore`.
