### ISSUE TITLE
Preview Images missing

### ISSUE THREAD

**Issue by ShalokShalom** [higan-emu/higan#198]
dead url https://github.com/higan-emu/higan#preview

See the last line :)

**Comment by ShalokShalom** [comment]
Oh, https://near.sh/ is also down. It is also mentioned in your README :)

**Comment by ShalokShalom** [comment]
The link to near's page is still up

**Comment by bikerspade** [comment]
@ShalokShalom the above pull request should fix it, not sure why the issue was closed as completed.
