### ISSUE TITLE
error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Blad3forc3** [higan-emu/higan#204]
Kubuntu 24.04

error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory

**Comment by Screwtapello** [comment]
Make sure you have the `libgtksourceview-3.0-1` package installed.

**Comment by Blad3forc3** [comment]
Fixed it thanks
