### ISSUE TITLE
Byuu and higan segfault on Linux with Dynamic Rate Control on Pulseaudio

### ISSUE THREAD

**Issue by jhlkek** [higan-emu/higan#24]
There was an issue for this on byuu's higan repository but unfortunately it's gone now.

Steps to reproduce:
1. Start byuu/higan on Linux
2. Switch to the PulseAudio audio driver
3. Enable dynamic rate control
4. Restart the program
5. Try to run a game

Byuu/higan will crash.

**Comment by Screwtapello** [comment]
Should be fixed by PR #25. Please re-open if this is not the case.
