### ISSUE TITLE
Compiling byuu as "accuracy" results in 70% larger binary and super low fps

### ISSUE THREAD

**Issue by FitzRoyX** [higan-emu/higan#26]
Possibly Windows specific, didn't get many volunteers on discord to confirm the issue anywhere. We know it doesn't happen for byuu under FreeBSD, though. Performance builds work fine. Note that the GBA doesn't have an accuracy core, but the fps still tanks from 100+ to 14.

![bb1](https://user-images.githubusercontent.com/57089001/78959733-82c57480-7ab1-11ea-9c73-7e563ea00ebc.png)
![bb2](https://user-images.githubusercontent.com/57089001/78959738-848f3800-7ab1-11ea-92ae-69fe6bd24fae.png)

**Comment by Screwtapello** [comment]
Some tests on Linux:

    $ make -C higan target=byuu profile=performance build=performance local=true
    $ du -h higan/out/byuu
    11M	higan/out/byuu
    $ git clean -dxf
    $ make -C higan target=byuu profile=accuracy build=performance local=true
    $ du -h higan/out/byuu
    11M	higan/out/byuu
    $ git clean -dxf
    $ make -C higan target=higan profile=performance build=performance local=true
    $ du -h higan/out/higan
    11M	higan/out/higan
    $ git clean -dxf
    $ make -C higan target=higan profile=accuracy build=performance local=true
    $ du -h higan/out/higan
    11M	higan/out/higan

So, I can't reproduce that issue here. Can you provide the exact `make` command you used to build each version, as I've done above?

**Comment by FitzRoyX** [comment]
So I know what I did wrong. For years, higan's makefile had profile settings at the top called accuracy and performance. Now there is "build" and "profile", and both have "performance". I was changing "build=performance" to "build=accuracy". So what is "build" and why does it still compile if I give it accuracy?

**Comment by Screwtapello** [comment]
I think we sorted this out on Discord, but for the benefit of anybody that arrives here via Google or similar: `profile` chooses the dot-based (slow, accurate) or scanline-based (fast, less accurate) renderer, for the emulation cores that include both options. `build` sets a bunch of related compiler flags to various points along the "optimized" ↔ "debuggable" spectrum. If you set `build` to some value it doesn't recognise, I'm not sure what happens.

These things definitely need to be better-documented, issue #31 will track that effort.
