### ISSUE TITLE
211b multiplication conflict with hdma

### ISSUE THREAD

**Issue by gizaha** [higan-emu/higan#50]
I think i found a serious bug in bsnes plus v05 debugger. I don't even know if i'm at the right place, please correct me.
I'm not saying about a minor graphic bug, i'm talking about wrong multiplication result (under condition). This might cause glitches to some games.

I have save states to reproduce it. Contact me for more.

**Comment by Screwtapello** [comment]
bsnes-plus is based on a very old version of higan, and is pretty much unrelated to modern higan/bsnes. You want https://github.com/devinacker/bsnes-plus instead.

**Comment by gizaha** [comment]
I used the version you gave me and the problem persists. Do you want to analyze the bug? Can i send you email with the save states?

**Comment by gizaha** [comment]
I used the version you gave me and the problem persists. Do you want to
analyze the bug? Can i send you email with the save states?

**Comment by gizaha** [comment]
And please don't close the case without asking questions first and listen what i have to say.

**Comment by Screwtapello** [comment]
I have not given anyone a copy of bsnes-plus, I don't know anything about it. You should file an issue at its official repository, which I linked above.

**Comment by gizaha** [comment]
I already did.
