### ISSUE TITLE
need argument support to libco

### ISSUE THREAD

**Issue by changloong** [higan-emu/higan#51]
It will be great to have one argument pass into the fiber entry function like this:

```c
cothread_t co_create(unsigned int size, void (*)(void*) callback, void* user_data);

void my_co(void* user_data){
      
}

struct my_data_t my_data = malloc(sizeof(struct my_data_t ));
cothread_t* handle = co_create(1024*1024, my_co, my_data);
```

Windows Fiber already has it.   Is there any one can give some tips, about the x86_64 `asm` change for this?

**Comment by Screwtapello** [comment]
Closing in favour of higan-emu/libco#16.
