### ISSUE TITLE
Low SNES and Game Boy Advance emulation performance

### ISSUE THREAD

**Issue by freq-mod** [higan-emu/higan#53]
On newest nightly build of higan, SA-1 games (for example, Super Mario RPG) and Super FX games (Doom) struggle to reach 40 fps. While understandable, given accuracy of this core, :

**- bsnes v115 seem to run these titles in stable 60 fps** EDIT: at least with "Coprocessors Fast mode" enabled, without it framerate rate drops to around 48-49 fps

**-"higan accuracy" core in RetroArch also doesn't have that problem either**

My CPU is Intel Core i5-2400 @ 3.1 GhZ with turbo speed of 3.3 GhZ. CPU load during emulation is ~35%, no power saving mode is enabled.

**Comment by Kawa-oneechan** [comment]
Can confirm that on my Intel Core i7-1065G7 @ 1.30 GHz, higan v110 *also* struggles with Doom, reaching roughly 45 to 55 fps.

...Wait. *Wait.*

Your *3.1* GHz runs Doom *slower* than my *1.30* GHz? 🤔

**Comment by freq-mod** [comment]
>Your 3.1 GHz runs Doom slower than my 1.30 GHz? 🤔

I also find it very hard to believe 🤷‍♂️ Simpler games like SMW run just fine, stable 60fps, while StarFox pushes 48 fps AT THE TITLE SCREEN (with 30% CPU load).

I might test performance of other systems.

**Comment by Kawa-oneechan** [comment]
At least the other things make sense: the SuperFX is a coprocessor so if you enable bsnes' "coprocessor fast mode", thus switching from a properly emulated SFX to a close approximation (from low-level to high-level emulation, the reason full speed N64 emulation was perfectly feasible back in the day), that cuts out a *lot* of effort and thus raises your FPS.

I don't know what version of mainline higan the RetroArch core you mentioned is most like, but clearly it's not trying to be as accurate as the actual higan, despite the name.

**Comment by freq-mod** [comment]
> if you enable bsnes' "coprocessor fast mode", thus switching from a properly emulated SFX to a close approximation (from low-level to high-level emulation

Regarding bsnes, there are two coprocessor emulation checkboxes - "Fast mode" and "Prefer HLE" - only first was checked, I didn't bother with HLE.

Also, RetroArch cores is based off higan v106, apparently.

About StarFox, yeah, bad example, my bad, sorry about that. Still, I don't know whether such performance on SFX and SA-1 games are normal with over 3GhZ quad-core CPU.
 I even took different PC: not-so-new notebook with Intel i3-5005U @ **2.0 GHz**, performance was expectedly even worse - 
Doom ran at 27 ~ 29 fps while Super Castlevania 4 barely pushed high 40s.

Rest of cores seem to work fine, except GBA - it's even more sluggish than SNES, but seems like there is a reason for that: 
>higan is roughly tied for the most accurate timing emulation for the Game Boy Advance, with extensive effort placed into ROM prefetch emulation, and the only pixel-based renderer in a GBA core.

**Comment by Kawa-oneechan** [comment]
I have reports of an i7-3770K 4.5 GHz running Doom in higan at 57-60 fps. By the very nature of what higan does and how it does these things, the best way to get it to run SFX games is to give up and *not use higan*, or throw more gigs at the wall. More cores won't help — this is not a multithreading application I believe, so you want the *one* core to be as fast as you can afford.

In other words, play it in bsnes instead.

**Comment by freq-mod** [comment]
I see. (*sigh*)
Looks like it can't be fixed and it's not a problem on my side (well, software-wise at least) Thanks for help anyways. _high time I invested in new CPU, I guess_

**Comment by UnfairMode** [comment]
I love Higan. Sad to see today we can't play Super Mario RPG with 60FPS yet. But I hope the best for this one.

**Comment by Kawa-oneechan** [comment]
> I love Higan. Sad to see today we can't play Super Mario RPG with 60FPS yet. But I hope the best for this one.

![SMRPG running at 60 FPS](https://github.com/higan-emu/higan/assets/12450280/5ec765e3-faae-4e97-b966-a5932446394a)
![Doom running at 60 FPS for good measure](https://github.com/higan-emu/higan/assets/12450280/fa4641cd-0cd5-41af-9fab-1103d69d38a3)

What are you on about? Higan doesn't get above 50, sure, but it's also not in active development anymore and Ares is the preferred system for Just Playing Stuff and it runs fine. That's what's in those screenshots.

**Comment by UnfairMode** [comment]
> > I love Higan. Sad to see today we can't play Super Mario RPG with 60FPS yet. But I hope the best for this one.
> 
> ![SMRPG running at 60 FPS](https://user-images.githubusercontent.com/12450280/261833721-5ec765e3-faae-4e97-b966-a5932446394a.png) ![Doom running at 60 FPS for good measure](https://user-images.githubusercontent.com/12450280/261833806-fa4641cd-0cd5-41af-9fab-1103d69d38a3.png)
> 
> What are you on about? Higan doesn't get above 50, sure, but it's also not in active development anymore and Ares is the preferred system for Just Playing Stuff and it runs fine. That's what's in those screenshots.

Higan V105 was doing a good job with 59FPS and some little drops (Super Mario RPG). I only found this new version (110 and 115) these days.
So I thought it was in development yet (my mistake sorry).

I'm going to try this Ares. Didn't know about this one. Thanks.
