### ISSUE TITLE
Decide on naming

### ISSUE THREAD

**Issue by byuu** [higan-emu/higan#7]
This is something I've given up on, but I wanted to note that I'll leave it to the future maintainers.

I'm sorry to have punted to you all on this issue. But it's an important one, so the earlier a decision is made, the better it will be for reducing the confusion I've caused.

# Background

higan-emu ships with two GUI targets: target-higan and target-byuu.

target-higan is built with pixel-based renderers (much slower, but more accurate) and has a very complex GUI that exposes the system state as a tree-view (to connect controllers, cartridges, etc.) This GUI allows for complex configurations like connecting Sonic 3 to Sonic & Knuckles to a Game Genie, or connecting Twin Taps to a Super Multitap adapter. But it has a steep learning curve and takes longer to use it. It is meant to preserve every facet of the original systems.

target-byuu is built with scanline-based renderers (much faster, needed for run-ahead to work well) and has a much easier to use, simplified GUI. You lose things like multi-cartridge stacking and per-system configurations. And as of my final release, it only supports one player controller for now, even though a two-player mode was planned. This one is meant for casual gamers and you can be up and playing just by dragging a game onto the program.

It is possible to build target-higan with scanline renderers, and target-byuu with pixel renderers, but I felt having four binaries would be too much confusion.

# Problem

I don't know if target-byuu should have been named eponymously (after myself) or not. It is likely to cause confusion. But similarly, if both targets were called higan, I believe that would cause far more confusion.

Both the names byuu and higan have a lot of connotations, good and bad. People remember me as byuu, and the slower, more complex GUI as higan.

I think our best shot here is probably to come up with an entirely new name for target-byuu, but the truth is that I've never been good at naming things, and if we choose a new name for it, we would have to create a new program icon and logo. This was too much work for me to do before stepping down.

In any case, I'm essentially handing the decision off to future maintainers: whether you all decide to keep the easy-mode GUI named "byuu", try to rebrand it as "higan" lite, or come up with a new name entirely ... all of these scenarios are okay with me. But I would unfortunately ask you all to decide what to do in my stead, and if the decision is one of the latter two options, to make the appropriate changes to the codebase to make it happen.

# Solutions

A) keep it as target-byuu
Pro: we don't have to change anything or get a new logo, nothing changes from how it is now
Con: it will cause confusion if and when I return, since I also go by the name byuu

B) rename it as target-higan-($something)
Pro: it makes the most sense since it is part of the higan-emu project in a single GitHub repository
Con: it will be even more confusing since it won't be clear *which* higan people are referring to online

C) rename it as target-($something-else)
Pro: this is the best option to distinguish the new user interface as its own unique program
Con: you will have to come up with a name, create an icon and logo, and then either keep it inside the higan-emu repository (confusing) or spin off a new, third repository just for it (a duplication of effort.)

D) rename both targets to something entirely new, and leave higan as the backend and GitHub project name [suggestion courtesy of moon-chilled]

Again, whatever you all decide, any option above is fine. Just, it's best to decide this as soon as we can. The longer we wait, the more difficult it will be to change course later on.

**Comment by Kawa-oneechan** [comment]
I can tell you already that if you go with C, "moeru" is apparently already taken, sort of.

**Comment by moon-chilled** [comment]
D) make higan be the 'umbrella' term for two emulators, ruby, nall, hiro, libco, and everything else.  Rename both the emulators.

**Comment by vilhelmgray** [comment]
As a user, I had difficulty understanding the difference between 'higan' and 'byuu' when it was first announced. Is 'byuu' essentially just a different interface? Yeah, the renderers in the prebuilt binaries are different but that's just a configuration when building.

If we are essentially just talking about different interfaces, then option D makes the most sense here: allow 'higan' to represent the backend, and rename the two interfaces. This makes the difference between the two emulators clear: they both share the same critical emulation code, but they are two different approaches to interfacing -- one focused on simplicity of gaming, and the other on complete preservation of device functionality.

As for the new names, I think they should reflect the purpose and philosophy of each interface. In the end we'll have three names (one for each component) so I would propose something like this:

* **higan** - backend for both interfaces
* **tanjun** - rename of 'byuu' interface; named after the Japanese word 単純 meaning "pure simplicity"
* **hozon** - rename of 'higan' interface; name after the Japanese word 保存 meaning "preservation"

By the way, this word **hozon** is also used in Japan in the context of saving something to a computer disk (e.g. ディスクに保存しておいて) so I find it a quite fitting name given how the goal is to preserve the functionality of all these gaming system devices and peripherals.

**Comment by FitzRoyX** [comment]
Instead of unleashing new and more names, I favor consolidation and reversion. Giving the slow interface the higan name and status was a mistake that can still be undone. It made the common man's interface some kind of secondary option, less searchable, less known, when it should've been the opposite. Rename byuu to higan and higan to higanx. Delete the byuu git and don't give higanx binary releases.

While I'd obviously prefer totally new names (that are more western like our audience), it's not worth trying to undo higan's lengthy existence.

**Comment by baraclese** [comment]
I'm not sure the byuu author / emulator mixup is much of an issue. Most people can't name a single emulator author. However higan itself should not be renamed because it has a long history. byuu could be renamed to higan-simple, but my vote is for keeping the name byuu because any name change is bound to introduce confusion for a while.

**Comment by AndersonTorres** [comment]
> It is possible to build target-higan with scanline renderers, and target-byuu with pixel renderers, but I felt having four binaries would be too much confusion.

My three cents here: if higan and byuu can be built with scanline or pixel renderers, then it can be made a compilation option exposed via config options. Meson (or any other decent build system) can expose them accordingly, and with way more accuracy and organization.

It is very related to the issue at #8 then.

**Comment by sards3** [comment]
Is there any reason that higan and byuu cannot be merged into one program? That way we could have the simple byuu interface as the default, with some way to toggle on the "expert mode" higan interface for more advanced tweaking and configuration.

**Comment by vilhelmgray** [comment]
Is the default renderer the only backend difference between the two?

**Comment by Screwtapello** [comment]
> if higan and byuu can be built with scanline or pixel renderers, then it can be made a compilation option exposed via config options

It's already a compilation option, which is how we (now) have automated higan and byuu nightly builds.

> Is there any reason that higan and byuu cannot be merged into one program?

It would make things *much* more complex to be able to dynamically switch between the high-level "byuu" interface and the lower-level "higan" interface. For example, "higan" is fundamentally based around the idea of constructing a directory tree on disk that describes a system and all the connected peripherals. "byuu" is fundamentally based on constructing a system description in-memory, that cannot represent all the possible variant's higan's model does. Switching in either direction would be a mess, never mind switching back and forth.

> Is the default renderer the only backend difference between the two?

Yes, and not every emulation core has a scanline-based renderer, so some consoles will be exactly the same (assuming issues like #26 get fixed).

----

Anyway, my strawman suggestions:

- "higan" → "higan Pro"
- "byuu" → "higan Lite"

**Comment by vilhelmgray** [comment]
Ah, I understand now. In that case, I'm going to retract my earlier suggestion of completely new names. Instead, I think keeping it as "higan" and differentiating between the simple and more complex interface is best.

"Lite" as a suffix may be okay, but I'd recommend something else besides "Pro" as I think that suffix holds an unintentional connotation of a proprietary version given its use in a lot of open core software models. Perhaps just leaving it as "higan" and "higan Lite" will be fine.

**Comment by Screwtapello** [comment]
Yeah, I picked "lite" first and cast about a bit for a counterpart that meant "more complex". Leaving the complex version of higan without a suffix is certainly possible, but given that current-higan and current-byuu share most code, it'd be nice to have a distinct name that refers to both of them so we don't have to ask "did you mean the complex UI, or both UIs?" every time. Especially since both UIs have moved away from the traditional higan v106 UI in opposite directions, it seems fitting to give the both new labels.

"higan Dev"? "higan 120%"? "higan Prime"? "higan Control"? "higan Grit"? "higan Zoom"? "higan Power"?

**Comment by vilhelmgray** [comment]
That's a good point, I can see how confusion could arise if there is no suffix. At the risk of bikeshedding further, I'd suggest the suffix be straightforward in meaning so it's intuitive which interface is which -- so perhaps "higan Advanced" or "higan Full" (something along those lines).

**Comment by Screwtapello** [comment]
I could get behind "higan Advanced". There's a risk people might assume it's just a GBA emulator, but that seems unlikely. "higan Plus" might have been nice, but "bsnes-plus" already exists, and we don't want people to assume that "higan Plus" has a debugger.

"higan Modular" might be another possibility.

**Comment by vilhelmgray** [comment]
"higan Modular" might be good since it avoid the connotation that "higan Advanced" is somehow better performing than "higan Lite" (which is not the case, it's just a different interface). "higan Modular" also has the useful benefit of making it obvious that it's the interface that allows you to configure all those neat esoteric game device add-ons and modules together.

**Comment by AndersonTorres** [comment]
"Higan Modular"? What? It looks like something experimental, not production-ready.

I think higan-full and higan-lite are better.

**Comment by CoreyVidal** [comment]
As a consumer, having a number of different titles comes with some figuring out.

Just to throw an idea out there:
The emulator itself I think should be the focus of the name. higan. I think that name should encompass everything. And you tell the public that higan has 2 modes/renderers/containers/kernals, or maybe "priority": -fast, and -accurate. Presented with those 2 options, it's clear the value that -accurate offers.

You can include a message like: "If you're not sure which one, start with 'higan-fast'".

Or:

"For casual players, you probably want higan-fast."

Something like that can make it less intimidating for new discoverers to jump in, without needing a history lesson.

Then for the GUI, you just present it as 2 different GUI options: -default and -advanced.

Again, this makes it really simple for onboarding new people. Again, the whole thing is called higan. Casual people discovering higan, who want to get up and running, would go with the -fast -default.

I don't think you need to worry about -advanced being confused with the Game Boy Advance, if -advanced is presented beside -default as one or the other.

Higan:
-fast -default: for casual players (start here)
-fast -advanced: for those wanting to expose console settings
-accurate -default: for a focus on accuracy
-accurate -advanced: for the most accurate experience possible

**Comment by Screwtapello** [comment]
A discussion of this topic recently erupted on the byuu.org discord. Some of the brainstormed names included:

- higan-simple and higan-extended
- higan Gamer Edition and higan Developer Edition
- higan-casual and higan-hardmode
- higan-expert (for the complex UI)
- higan-custom (for the complex UI)
- higan X and higan SE
- higan-a-rank and higan-s-rank
- higan-engineering (for the complex UI)
- higan-player and higan-homebrew
- higan-play and higan-brew

Not all of those suggestions are equally serious, but some of them have promise. In particular, I currently like higan-play and higan-brew for being short, fairly obvious without explanation, and not having the value-judgement connotations of things like "casual" or "pro" or "advanced".

**Comment by near-san** [comment]
I have a proposal that may be able to wrap this up, and have it be our best shot at reducing naming complexity.

higan-emu ships with the complex tree-based GUI, compiled with the accuracy profile => higan.exe

ares-emu ships with the simplified list-based GUI, compiled with the performance profile => ares.exe

If people want to remix their own builds: higan with the performance profile, ares with the accuracy profile, higan with the list-based GUI, ares with the tree-basd GUI, etc ... that's fine and up to them.

But by having a specific set of goals for higan and ares, we distinguish them as separate sister projects.

We do away publicly with referring to higan-ui / luna and byuu / lucia. The user interface names become an internal detail once again, similar to tomoko and ethos from past iterations.

I'm not advocating we rush to remove all traces of the list-based GUI from higan-emu, but we can make this a milestone for v116 if everyone is in agreement. Thoughts?

**Comment by Screwtapello** [comment]
Closing this issue since the "byuu" UI has been removed from higan, which means we just have one UI again which can unambiguously be named "higan". We still have "higan" and "higan-ui" directories, but that can be cleaned up later.

**Comment by Screwtapello** [comment]
Thanks to Near, we've removed the simple UI from higan altogether, making this No Longer A Problem - there's just one UI and it's called "higan".
