### ISSUE TITLE
Streets of Rage 2 Graphics Glitches in Lucia v115 (Performance Profile)

### ISSUE THREAD

**Issue by yepimbonez** [higan-emu/higan#76]
As the title suggests, Streets of Rage 2 was having some issues rendering properly.  During gameplay, while the background seemed to render ok, any moving object on screen would dissolve into a mosaic graphical mess.  Compiling the source with the accuracy profile seemed to fix all issues.  I did test a couple other games, like Sonic the Hedgehog 2 and Golden Axe.  Both of those seemed to work well either way.

**Right away the selection arrow was missing:**
![Screenshot 8_18_2020 12_45_57 AM](https://user-images.githubusercontent.com/69835109/90471944-62f02e00-e0ed-11ea-918a-4f184a241dd2.png)

**Fixed version:**
![Screenshot 8_18_2020 12_49_29 AM](https://user-images.githubusercontent.com/69835109/90472029-8adf9180-e0ed-11ea-81e5-5ee010c1aa68.png)

**And the character selection screen was a mess:**
![Screenshot 8_18_2020 12_46_09 AM](https://user-images.githubusercontent.com/69835109/90471945-62f02e00-e0ed-11ea-8848-782a953620e4.png)

**Fixed version:**
![Screenshot 8_18_2020 12_49_34 AM](https://user-images.githubusercontent.com/69835109/90472030-8adf9180-e0ed-11ea-9ea5-55f0f6726210.png)

**Comment by Screwtapello** [comment]
The "performance" profile has been removed, since we want higan to focus on accuracy. Near will be maintaining those profiles in his "ares" emulator going forward.
