### ISSUE TITLE
GBC: Enemies appear over the hotbar in The Legend of Zelda - Oracle of Ages

### ISSUE THREAD

**Issue by SilasLaspada** [higan-emu/higan#97]
In The Legend of Zelda - Oracle of Ages, enemies appear over the hotbar but under items in the hotbar.
![byuu_Gk0auFAFwD](https://user-images.githubusercontent.com/24215969/92382642-28652a00-f0ca-11ea-92aa-9b28984e7153.png)

**Comment by SilasLaspada** [comment]
Applies to dialog boxes as well
![byuu_iZtZgHK5NI](https://user-images.githubusercontent.com/24215969/92382805-75e19700-f0ca-11ea-8078-7364efdc337a.png)

**Comment by Screwtapello** [comment]
This should be fixed by #102, I'm not sure why GitHub didn't automatically close this.
